-- V002__generate_dummy_raw_data.sql


TRUNCATE TABLE AE_ATTENDANCE_RAW;

INSERT INTO AE_ATTENDANCE_RAW (
  ATTENDANCE_ID, NHS_NUMBER, HOSPITAL_SITE_CODE, TRUST_CODE,
  PATIENT_DOB, PATIENT_AGE, PATIENT_GENDER, PATIENT_POSTCODE,
  ARRIVAL_TS, TRIAGE_TS, FIRST_CLINICIAN_TS, DISCHARGE_TS,
  ARRIVAL_MODE, CHIEF_COMPLAINT, DIAGNOSIS_CODE, DIAGNOSIS_DESC,
  WAIT_MINS_TO_TRIAGE, WAIT_MINS_TO_CLINICIAN, TOTAL_LOS_MINS,
  FOUR_HOUR_BREACH_FLAG
)
WITH BASE AS (
  SELECT
    SEQ4() AS RN,
    DATEADD('day', -UNIFORM(0, 60, RANDOM()), CURRENT_DATE()) AS ARRIVAL_DATE,
    UNIFORM(0, 23, RANDOM()) AS ARRIVAL_HOUR,
    UNIFORM(0, 59, RANDOM()) AS ARRIVAL_MIN
  FROM TABLE(GENERATOR(ROWCOUNT => 200))
),
TS AS (
  SELECT
    RN,
    TO_TIMESTAMP_NTZ(TO_VARCHAR(ARRIVAL_DATE) || ' ' ||
      LPAD(ARRIVAL_HOUR::STRING, 2, '0') || ':' || LPAD(ARRIVAL_MIN::STRING, 2, '0') || ':00') AS ARRIVAL_TS,
    DATEADD('minute', UNIFORM(0, 45, RANDOM()),
      TO_TIMESTAMP_NTZ(TO_VARCHAR(ARRIVAL_DATE) || ' ' ||
      LPAD(ARRIVAL_HOUR::STRING, 2, '0') || ':' || LPAD(ARRIVAL_MIN::STRING, 2, '0') || ':00')) AS TRIAGE_TS,
    DATEADD('minute', UNIFORM(10, 240, RANDOM()),
      TO_TIMESTAMP_NTZ(TO_VARCHAR(ARRIVAL_DATE) || ' ' ||
      LPAD(ARRIVAL_HOUR::STRING, 2, '0') || ':' || LPAD(ARRIVAL_MIN::STRING, 2, '0') || ':00')) AS FIRST_CLINICIAN_TS,
    DATEADD('minute', UNIFORM(30, 600, RANDOM()),
      TO_TIMESTAMP_NTZ(TO_VARCHAR(ARRIVAL_DATE) || ' ' ||
      LPAD(ARRIVAL_HOUR::STRING, 2, '0') || ':' || LPAD(ARRIVAL_MIN::STRING, 2, '0') || ':00')) AS DISCHARGE_TS
  FROM BASE
),
PATIENTS AS (
  SELECT
    RN,
    LPAD(UNIFORM(100000000, 999999999, RANDOM())::STRING, 10, '0') AS NHS_NUMBER_OK,
    DATEADD('year', -UNIFORM(0, 95, RANDOM()), DATEADD('day', -UNIFORM(0, 364, RANDOM()), CURRENT_DATE())) AS DOB_OK,
    UNIFORM(0, 95, RANDOM()) AS AGE_OK,
    IFF(UNIFORM(0, 10, RANDOM()) < 5, 'F', 'M') AS GENDER_OK,
    IFF(UNIFORM(0, 10, RANDOM()) < 5, 'NW1 2DB', 'WC1E 6BT') AS POSTCODE_OK
  FROM BASE
),
CODES AS (
  SELECT
    RN,
    IFF(UNIFORM(0, 10, RANDOM()) < 5, 'R1H12', 'R1K01') AS SITE_OK,
    IFF(UNIFORM(0, 10, RANDOM()) < 5, 'RJZ', 'RKE') AS TRUST_OK,
    IFF(UNIFORM(0, 10, RANDOM()) < 4, 'Ambulance', IFF(UNIFORM(0, 10, RANDOM()) < 8, 'Walk-in', 'Other')) AS ARRIVAL_MODE_OK,
    IFF(UNIFORM(0, 10, RANDOM()) < 3, 'Chest pain',
      IFF(UNIFORM(0, 10, RANDOM()) < 6, 'Shortness of breath',
      IFF(UNIFORM(0, 10, RANDOM()) < 8, 'Abdominal pain', 'Head injury'))) AS COMPLAINT_OK,
    IFF(UNIFORM(0, 10, RANDOM()) < 3, 'R07.9',
      IFF(UNIFORM(0, 10, RANDOM()) < 6, 'R06.0',
      IFF(UNIFORM(0, 10, RANDOM()) < 8, 'R10.4', 'S09.90'))) AS DIAG_CODE_OK
  FROM BASE
),
DIAG AS (
  SELECT
    RN,
    CASE DIAG_CODE_OK
      WHEN 'R07.9' THEN 'Chest pain, unspecified'
      WHEN 'R06.0' THEN 'Dyspnoea'
      WHEN 'R10.4' THEN 'Other and unspecified abdominal pain'
      WHEN 'S09.90' THEN 'Unspecified injury of head, initial encounter'
      ELSE 'Unknown'
    END AS DIAG_DESC_OK
  FROM CODES
),
ASSEMBLED AS (
  SELECT
    T.RN,
    IFF(MOD(T.RN, 50) = 0, 'AE-' || LPAD((T.RN - 1)::STRING, 6, '0'), 'AE-' || LPAD(T.RN::STRING, 6, '0')) AS ATTENDANCE_ID,
    IFF(MOD(T.RN, 17) = 0, NULL,
      IFF(MOD(T.RN, 29) = 0, '12345', P.NHS_NUMBER_OK)
    ) AS NHS_NUMBER,
    C.SITE_OK AS HOSPITAL_SITE_CODE,
    C.TRUST_OK AS TRUST_CODE,
    IFF(MOD(T.RN, 41) = 0, DATEADD('day', 10, CURRENT_DATE()), P.DOB_OK) AS PATIENT_DOB,
    IFF(MOD(T.RN, 37) = 0, 210,
      IFF(MOD(T.RN, 19) = 0, -3, P.AGE_OK)
    ) AS PATIENT_AGE,
    IFF(MOD(T.RN, 23) = 0, 'X',
      IFF(MOD(T.RN, 31) = 0, NULL, P.GENDER_OK)
    ) AS PATIENT_GENDER,
    IFF(MOD(T.RN, 13) = 0, 'INVALID', P.POSTCODE_OK) AS PATIENT_POSTCODE,
    IFF(MOD(T.RN, 53) = 0, DATEADD('day', 7, T.ARRIVAL_TS), T.ARRIVAL_TS) AS ARRIVAL_TS,
    IFF(MOD(T.RN, 47) = 0, DATEADD('minute', -15, T.ARRIVAL_TS), T.TRIAGE_TS) AS TRIAGE_TS,
    IFF(MOD(T.RN, 43) = 0, DATEADD('minute', -10, T.TRIAGE_TS), T.FIRST_CLINICIAN_TS) AS FIRST_CLINICIAN_TS,
    IFF(MOD(T.RN, 11) = 0, NULL, T.DISCHARGE_TS) AS DISCHARGE_TS,
    IFF(MOD(T.RN, 27) = 0, 'Teleport', C.ARRIVAL_MODE_OK) AS ARRIVAL_MODE,
    C.COMPLAINT_OK AS CHIEF_COMPLAINT,
    C.DIAG_CODE_OK AS DIAGNOSIS_CODE,
    D.DIAG_DESC_OK AS DIAGNOSIS_DESC,
    IFF(MOD(T.RN, 21) = 0, -5, DATEDIFF('minute', T.ARRIVAL_TS, T.TRIAGE_TS)) AS WAIT_MINS_TO_TRIAGE,
    IFF(MOD(T.RN, 33) = 0, 99999, DATEDIFF('minute', T.ARRIVAL_TS, T.FIRST_CLINICIAN_TS)) AS WAIT_MINS_TO_CLINICIAN,
    IFF(MOD(T.RN, 39) = 0, -60,
      IFF(T.DISCHARGE_TS IS NULL, NULL, DATEDIFF('minute', T.ARRIVAL_TS, T.DISCHARGE_TS))
    ) AS TOTAL_LOS_MINS,
    IFF(MOD(T.RN, 25) = 0, 'Maybe',
      IFF(DATEDIFF('minute', T.ARRIVAL_TS, T.DISCHARGE_TS) > 240, 'Y', 'N')
    ) AS FOUR_HOUR_BREACH_FLAG
  FROM TS T
  JOIN PATIENTS P ON P.RN = T.RN
  JOIN CODES C ON C.RN = T.RN
  JOIN DIAG D ON D.RN = T.RN
)
SELECT
  ATTENDANCE_ID, NHS_NUMBER, HOSPITAL_SITE_CODE, TRUST_CODE,
  PATIENT_DOB, PATIENT_AGE, PATIENT_GENDER, PATIENT_POSTCODE,
  ARRIVAL_TS, TRIAGE_TS, FIRST_CLINICIAN_TS, DISCHARGE_TS,
  ARRIVAL_MODE, CHIEF_COMPLAINT, DIAGNOSIS_CODE, DIAGNOSIS_DESC,
  WAIT_MINS_TO_TRIAGE, WAIT_MINS_TO_CLINICIAN, TOTAL_LOS_MINS,
  FOUR_HOUR_BREACH_FLAG
FROM ASSEMBLED;
