INSERT INTO AE_ATTENDANCE_DQ_ISSUES (ATTENDANCE_ID, ISSUE_TYPE, ISSUE_DETAIL, ISSUE_SEVERITY)
SELECT
  ATTENDANCE_ID,
  'TRUST_CODE_NULL',
  'TRUST_CODE is NULL',
  'ERROR'
FROM AE_ATTENDANCE_RAW
WHERE TRUST_CODE IS NULL;
