-- ============================================================
-- NHS-GRADE SNOWFLAKE CI/CD DEMO SETUP (ONE ACCOUNT, 3 DBs)
-- Creates: warehouses, databases/schemas, deploy roles, CICD users
-- NOTE: You still need to set RSA_PUBLIC_KEY after creating users.
-- ============================================================

-- -----------------------------
-- SECTION 1: Platform objects (SYSADMIN)
-- -----------------------------
-- USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS WH_DEV
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS WH_UAT
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS WH_PROD
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS NHS_DEV;
CREATE DATABASE IF NOT EXISTS NHS_UAT;
CREATE DATABASE IF NOT EXISTS NHS_PROD;

CREATE SCHEMA IF NOT EXISTS NHS_DEV.AE;
CREATE SCHEMA IF NOT EXISTS NHS_UAT.AE;
CREATE SCHEMA IF NOT EXISTS NHS_PROD.AE;

-- -----------------------------
-- SECTION 2: Security objects (SECURITYADMIN)
-- -----------------------------
-- USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS ROLE_DEV_DEPLOY;
CREATE ROLE IF NOT EXISTS ROLE_UAT_DEPLOY;
CREATE ROLE IF NOT EXISTS ROLE_PROD_DEPLOY;

-- DEV
GRANT USAGE ON WAREHOUSE WH_DEV TO ROLE ROLE_DEV_DEPLOY;
GRANT USAGE ON DATABASE NHS_DEV TO ROLE ROLE_DEV_DEPLOY;
GRANT USAGE ON SCHEMA NHS_DEV.AE TO ROLE ROLE_DEV_DEPLOY;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE SEQUENCE
  ON SCHEMA NHS_DEV.AE TO ROLE ROLE_DEV_DEPLOY;

-- UAT
GRANT USAGE ON WAREHOUSE WH_UAT TO ROLE ROLE_UAT_DEPLOY;
GRANT USAGE ON DATABASE NHS_UAT TO ROLE ROLE_UAT_DEPLOY;
GRANT USAGE ON SCHEMA NHS_UAT.AE TO ROLE ROLE_UAT_DEPLOY;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE SEQUENCE
  ON SCHEMA NHS_UAT.AE TO ROLE ROLE_UAT_DEPLOY;

-- PROD
GRANT USAGE ON WAREHOUSE WH_PROD TO ROLE ROLE_PROD_DEPLOY;
GRANT USAGE ON DATABASE NHS_PROD TO ROLE ROLE_PROD_DEPLOY;
GRANT USAGE ON SCHEMA NHS_PROD.AE TO ROLE ROLE_PROD_DEPLOY;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE SEQUENCE
  ON SCHEMA NHS_PROD.AE TO ROLE ROLE_PROD_DEPLOY;

-- CICD users (passwordless; set RSA keys next)
CREATE USER IF NOT EXISTS CICD_DEV
  DEFAULT_ROLE = ROLE_DEV_DEPLOY
  DEFAULT_WAREHOUSE = WH_DEV
  MUST_CHANGE_PASSWORD = FALSE;

CREATE USER IF NOT EXISTS CICD_UAT
  DEFAULT_ROLE = ROLE_UAT_DEPLOY
  DEFAULT_WAREHOUSE = WH_UAT
  MUST_CHANGE_PASSWORD = FALSE;

CREATE USER IF NOT EXISTS CICD_PROD
  DEFAULT_ROLE = ROLE_PROD_DEPLOY
  DEFAULT_WAREHOUSE = WH_PROD
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE ROLE_DEV_DEPLOY  TO USER CICD_DEV;
GRANT ROLE ROLE_UAT_DEPLOY  TO USER CICD_UAT;
GRANT ROLE ROLE_PROD_DEPLOY TO USER CICD_PROD;

-- Paste PUBLIC keys:
-- ALTER USER CICD_DEV  SET RSA_PUBLIC_KEY='-----BEGIN PUBLIC KEY-----...-----END PUBLIC KEY-----';
-- ALTER USER CICD_UAT  SET RSA_PUBLIC_KEY='-----BEGIN PUBLIC KEY-----...-----END PUBLIC KEY-----';
-- ALTER USER CICD_PROD SET RSA_PUBLIC_KEY='-----BEGIN PUBLIC KEY-----...-----END PUBLIC KEY-----';
